<?php

return [
    'برند' => ['Apple', 'Samsung', 'Lenovo', 'Hp', 'Microsoft'],
    'تاریخ_عرضه' => [],
    'وزن' => [],
    'ابعاد' => [],
    'توضیحات_بدنه' => [],
    'وبکم' => [],
    'نمایشگر' => [],
    'نرخ_تازه‌سازی' => [],
    'روشنایی_نمایشگر' => [],
    'چگالی' => [],
    'پردازنده' => [
        'Intel Celeron N4020',
        'Intel Celeron N4500',
        'Intel Pentium Silver N6000',
        'Intel Core i3 1115G4',
        'Intel Core i3 1215U',
        'Intel Core i5 1135G7',
        'Intel Core i5 1235U',
        'Intel Core i5 12450H',
        'Intel Core i7 1165G7',
        'Intel Core i7 1255U',
        'Intel Core i7 12700H',
        'Intel Core i9 12900H',

        'AMD Ryzen 3 3250U',
        'AMD Ryzen 3 5300U',
        'AMD Ryzen 5 3500U',
        'AMD Ryzen 5 5500U',
        'AMD Ryzen 5 5600H',
        'AMD Ryzen 7 4700U',
        'AMD Ryzen 7 5700U',
        'AMD Ryzen 7 5800H',
        'AMD Ryzen 9 5900HX',
    ],
    'تعداد_هسته' => [],
    'کارت گرافیک' => [
        'Intel UHD Graphics',
        'Intel Iris Xe',
        'NVIDIA GeForce MX450',
        'NVIDIA GeForce GTX 1650',
        'NVIDIA GeForce RTX 2050',
        'NVIDIA GeForce RTX 3050',
        'NVIDIA GeForce RTX 3060',
        'NVIDIA GeForce RTX 3070',
        'NVIDIA GeForce RTX 4050',
        'NVIDIA GeForce RTX 4060',
        'NVIDIA GeForce RTX 4070',
        'AMD Radeon Vega 7',
        'AMD Radeon RX 6500M',
        'AMD Radeon RX 6600M',
        'AMD Radeon RX 7600M',
    ],
    'پردازنده' => ['M1', 'i5', 'i7', 'snap-dragon 8'],
    'حافظه' => ['256GB', '512GB', '1TB', '2TB'],
    'رم' => ['2GB', '4GB', '6GB', '8GB', '16GB', '32GB', '64GB'],
    'کش' => [],
    'شبکه' => [],
    'پورت‌ها' => [],
    'سیم‌کارت' => [],
    'حسگر_اثر_انگشت' => [],
    'باتری' => [],
    'توان_شارژ' => [],
    'اقلام_همراه' => [],
];