<?php

return [
    'تاریخ_عرضه' => [],
    'وزن' => [],
    'ابعاد' => [],
    'توضیحات_بدنه' => [],
    'وبکم' => [],
    'نمایشگر' => [],
    'نرخ_تازه‌سازی' => [],
    'روشنایی_نمایشگر' => [],
    'چگالی' => [],
    'پردازنده' => [
            'A13 Bionic',
            'A14 Bionic',
            'A15 Bionic',
            'A16 Bionic',
            'A17 Pro',

            'Snapdragon 680',
            'Snapdragon 695',
            'Snapdragon 732G',
            'Snapdragon 778G',
            'Snapdragon 7 Gen 1',
            'Snapdragon 7+ Gen 2',
            'Snapdragon 8 Gen 1',
            'Snapdragon 8+ Gen 1',
            'Snapdragon 8 Gen 2',
            'Snapdragon 8 Gen 3',

            'Dimensity 700',
            'Dimensity 810',
            'Dimensity 900',
            'Dimensity 1080',
            'Dimensity 1200',
            'Dimensity 1300',
            'Dimensity 8200',
            'Dimensity 9000',
            'Dimensity 9200',

            'Exynos 850',
            'Exynos 1280',
            'Exynos 1380',
            'Exynos 2100',
            'Exynos 2200',
            'Exynos 2400',

    ],
    'تعداد_هسته' => [
        '4 هسته‌ای',
        '6 هسته‌ای',
        '8 هسته‌ای',
        '10 هسته‌ای',
    ],
    'کارت_گرافیک' => [
        'Apple GPU',
        'Adreno 610',
        'Adreno 619',
        'Adreno 642L',
        'Adreno 650',
        'Adreno 660',
        'Adreno 710',
        'Adreno 730',
        'Adreno 740',

        'Mali G52',
        'Mali G57',
        'Mali G68',
        'Mali G77',
        'Mali G78',
        'Mali G710',
        'Mali G715',

        'Xclipse 920',
        'Xclipse 940',
    ],
    'حافظه' => ['256GB', '512GB', '1TB', '2TB'],
    'رم' => ['2GB', '4GB', '6GB', '8GB', '16GB', '32GB', '64GB'],
    'کش' => [],
    'شبکه' => ['5G', '4G', '3G', 'LTE', '2G'],
    'پورت‌ها' => [],
    'سیم‌کارت' => [],
    'حسگر_اثر_انگشت' => [],
    'باتری' => [],
    'توان_شارژ' => [],
    'اقلام_همراه' => [],
];

?>